// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app_type_name`, `architecture_name`, `panic_message`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// The bridge's own version. Synchronous, so it doubles as a cheap round-trip check.
String bridgeVersion() => RustLib.instance.api.crateApiAppBridgeVersion();

/// Inspect an AppImage through the core's inspection pipeline. Never executes it.
Future<InspectSummary> inspectPath({required String path}) =>
    RustLib.instance.api.crateApiAppInspectPath(path: path);

/// Emit `0..total` on a stream, one value every 20 ms. Shows that a long Rust
/// operation can report progress without blocking the Dart isolate.
Stream<int> countTicks({required int total}) =>
    RustLib.instance.api.crateApiAppCountTicks(total: total);

/// Panics on purpose and proves the containment rule: a Rust panic reaches Dart
/// as a `CoreError` of kind `Internal` and does not end the process.
/// Spike-only; remove before the bridge is used by real pages.
Future<int> panicForContractTest() =>
    RustLib.instance.api.crateApiAppPanicForContractTest();

/// A typed core failure. `message` is safe to show; `details` is for the log only.
class CoreError implements FrbException {
  final ErrorKind kind;
  final String message;
  final String details;

  const CoreError({
    required this.kind,
    required this.message,
    required this.details,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode ^ details.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          details == other.details;
}

/// The failure kinds the front end distinguishes (design doc, section 6).
enum ErrorKind {
  userInput,
  validation,
  notFound,
  permission,
  corruptData,
  internal,
}

/// The result of inspecting one file. Read-only: nothing is installed or executed.
class InspectSummary {
  final String path;
  final BigInt sizeBytes;
  final String sha256;
  final String appType;
  final String architecture;
  final bool magicValid;
  final bool architectureSupported;
  final String name;
  final List<String> warnings;

  const InspectSummary({
    required this.path,
    required this.sizeBytes,
    required this.sha256,
    required this.appType,
    required this.architecture,
    required this.magicValid,
    required this.architectureSupported,
    required this.name,
    required this.warnings,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      sizeBytes.hashCode ^
      sha256.hashCode ^
      appType.hashCode ^
      architecture.hashCode ^
      magicValid.hashCode ^
      architectureSupported.hashCode ^
      name.hashCode ^
      warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InspectSummary &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          sizeBytes == other.sizeBytes &&
          sha256 == other.sha256 &&
          appType == other.appType &&
          architecture == other.architecture &&
          magicValid == other.magicValid &&
          architectureSupported == other.architectureSupported &&
          name == other.name &&
          warnings == other.warnings;
}
