// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `begin`, `cancel_flag`, `cancel_operation`, `classify`, `complete`, `controller`, `finish`, `guard`, `new`, `operations`, `panic_message`, `progress`, `task_id_of`, `tasks_guard`, `with_tasks`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OperationGuard`, `Operation`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `drop`, `eq`, `fmt`, `fmt`, `fmt`

/// A failure the front end cannot turn into an operation outcome. `message` is
/// user-safe; `details` is for the log only.
class CoreError implements FrbException {
  final ErrorKind kind;
  final String message;
  final String details;

  const CoreError({
    required this.kind,
    required this.message,
    required this.details,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode ^ details.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          details == other.details;
}

/// The failure kinds the front end distinguishes (design doc, section 6).
enum ErrorKind {
  userInput,
  validation,
  notFound,
  permission,
  corruptData,
  network,
  process,
  failure,
  internal,
}
