// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failure_fields`, `from_core`, `from_core`, `from_core`, `from_core`, `from_core`, `from_integrate`, `from_removal`, `hex_string`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// One AppImage the manager tracks, as shown on the Library and Details pages.
class AppDto {
  final String uuid;
  final String name;
  final String version;
  final String comment;
  final String managedPath;
  final String desktopId;
  final String desktopPath;
  final String iconPath;
  final String sha256;
  final String appType;
  final String architecture;
  final PlatformInt64 sizeBytes;
  final List<String> arguments;
  final List<EnvVarDto> environment;
  final String updateManager;
  final List<KeyValueDto> updateConfig;
  final String embeddedUpdate;
  final String lastUpdateCheck;
  final String availableVersion;
  final String availableUrl;
  final PlatformInt64 availableSize;
  final bool updateAvailable;
  final String digest;
  final bool reducedVerification;
  final bool running;
  final bool externalFolder;
  final bool owned;
  final bool adopted;
  final String website;
  final bool terminal;
  final List<String> categories;
  final List<String> mimeTypes;
  final String startupWmClass;
  final List<String> actionNames;

  const AppDto({
    required this.uuid,
    required this.name,
    required this.version,
    required this.comment,
    required this.managedPath,
    required this.desktopId,
    required this.desktopPath,
    required this.iconPath,
    required this.sha256,
    required this.appType,
    required this.architecture,
    required this.sizeBytes,
    required this.arguments,
    required this.environment,
    required this.updateManager,
    required this.updateConfig,
    required this.embeddedUpdate,
    required this.lastUpdateCheck,
    required this.availableVersion,
    required this.availableUrl,
    required this.availableSize,
    required this.updateAvailable,
    required this.digest,
    required this.reducedVerification,
    required this.running,
    required this.externalFolder,
    required this.owned,
    required this.adopted,
    required this.website,
    required this.terminal,
    required this.categories,
    required this.mimeTypes,
    required this.startupWmClass,
    required this.actionNames,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      name.hashCode ^
      version.hashCode ^
      comment.hashCode ^
      managedPath.hashCode ^
      desktopId.hashCode ^
      desktopPath.hashCode ^
      iconPath.hashCode ^
      sha256.hashCode ^
      appType.hashCode ^
      architecture.hashCode ^
      sizeBytes.hashCode ^
      arguments.hashCode ^
      environment.hashCode ^
      updateManager.hashCode ^
      updateConfig.hashCode ^
      embeddedUpdate.hashCode ^
      lastUpdateCheck.hashCode ^
      availableVersion.hashCode ^
      availableUrl.hashCode ^
      availableSize.hashCode ^
      updateAvailable.hashCode ^
      digest.hashCode ^
      reducedVerification.hashCode ^
      running.hashCode ^
      externalFolder.hashCode ^
      owned.hashCode ^
      adopted.hashCode ^
      website.hashCode ^
      terminal.hashCode ^
      categories.hashCode ^
      mimeTypes.hashCode ^
      startupWmClass.hashCode ^
      actionNames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          version == other.version &&
          comment == other.comment &&
          managedPath == other.managedPath &&
          desktopId == other.desktopId &&
          desktopPath == other.desktopPath &&
          iconPath == other.iconPath &&
          sha256 == other.sha256 &&
          appType == other.appType &&
          architecture == other.architecture &&
          sizeBytes == other.sizeBytes &&
          arguments == other.arguments &&
          environment == other.environment &&
          updateManager == other.updateManager &&
          updateConfig == other.updateConfig &&
          embeddedUpdate == other.embeddedUpdate &&
          lastUpdateCheck == other.lastUpdateCheck &&
          availableVersion == other.availableVersion &&
          availableUrl == other.availableUrl &&
          availableSize == other.availableSize &&
          updateAvailable == other.updateAvailable &&
          digest == other.digest &&
          reducedVerification == other.reducedVerification &&
          running == other.running &&
          externalFolder == other.externalFolder &&
          owned == other.owned &&
          adopted == other.adopted &&
          website == other.website &&
          terminal == other.terminal &&
          categories == other.categories &&
          mimeTypes == other.mimeTypes &&
          startupWmClass == other.startupWmClass &&
          actionNames == other.actionNames;
}

/// The outcome of "update all": applied, failed and skipped apps by name.
class BatchDto {
  final List<String> applied;
  final List<UpdateFailureDto> failed;
  final List<String> skippedRunning;
  final List<UpdateFailureDto> checkFailures;
  final bool cancelled;

  const BatchDto({
    required this.applied,
    required this.failed,
    required this.skippedRunning,
    required this.checkFailures,
    required this.cancelled,
  });

  @override
  int get hashCode =>
      applied.hashCode ^
      failed.hashCode ^
      skippedRunning.hashCode ^
      checkFailures.hashCode ^
      cancelled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchDto &&
          runtimeType == other.runtimeType &&
          applied == other.applied &&
          failed == other.failed &&
          skippedRunning == other.skippedRunning &&
          checkFailures == other.checkFailures &&
          cancelled == other.cancelled;
}

class DiscoveredDto {
  final String path;
  final String name;
  final bool managed;
  final String uuid;
  final bool externalDesktopEntry;
  final String desktopPath;

  const DiscoveredDto({
    required this.path,
    required this.name,
    required this.managed,
    required this.uuid,
    required this.externalDesktopEntry,
    required this.desktopPath,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      managed.hashCode ^
      uuid.hashCode ^
      externalDesktopEntry.hashCode ^
      desktopPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          managed == other.managed &&
          uuid == other.uuid &&
          externalDesktopEntry == other.externalDesktopEntry &&
          desktopPath == other.desktopPath;
}

class EnvVarDto {
  final String name;
  final String value;

  const EnvVarDto({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnvVarDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

/// Facts about one file, as the Inspect page shows them. Nothing is installed
/// or executed to produce it.
class InspectDto {
  final String path;
  final PlatformInt64 sizeBytes;
  final String sha256;
  final String appType;
  final String architecture;
  final bool magicValid;
  final bool architectureSupported;
  final bool truncated;
  final String name;
  final String version;
  final String comment;
  final String iconName;
  final String iconFormat;
  final Uint8List? iconBytes;
  final List<String> categories;
  final List<String> mimeTypes;
  final bool terminal;
  final String website;
  final String startupWmClass;
  final List<String> actionNames;
  final String embeddedUpdate;
  final String embeddedManagerHint;
  final List<String> warnings;
  final String error;
  final bool alreadyManaged;
  final String existingUuid;
  final String conflictStatus;
  final String conflictingUuid;
  final String conflictingName;
  final bool needsConflictDecision;
  final bool canReplace;
  final String plannedTarget;
  final String extractorUsed;
  final bool usedUnsafeFallback;

  const InspectDto({
    required this.path,
    required this.sizeBytes,
    required this.sha256,
    required this.appType,
    required this.architecture,
    required this.magicValid,
    required this.architectureSupported,
    required this.truncated,
    required this.name,
    required this.version,
    required this.comment,
    required this.iconName,
    required this.iconFormat,
    this.iconBytes,
    required this.categories,
    required this.mimeTypes,
    required this.terminal,
    required this.website,
    required this.startupWmClass,
    required this.actionNames,
    required this.embeddedUpdate,
    required this.embeddedManagerHint,
    required this.warnings,
    required this.error,
    required this.alreadyManaged,
    required this.existingUuid,
    required this.conflictStatus,
    required this.conflictingUuid,
    required this.conflictingName,
    required this.needsConflictDecision,
    required this.canReplace,
    required this.plannedTarget,
    required this.extractorUsed,
    required this.usedUnsafeFallback,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      sizeBytes.hashCode ^
      sha256.hashCode ^
      appType.hashCode ^
      architecture.hashCode ^
      magicValid.hashCode ^
      architectureSupported.hashCode ^
      truncated.hashCode ^
      name.hashCode ^
      version.hashCode ^
      comment.hashCode ^
      iconName.hashCode ^
      iconFormat.hashCode ^
      iconBytes.hashCode ^
      categories.hashCode ^
      mimeTypes.hashCode ^
      terminal.hashCode ^
      website.hashCode ^
      startupWmClass.hashCode ^
      actionNames.hashCode ^
      embeddedUpdate.hashCode ^
      embeddedManagerHint.hashCode ^
      warnings.hashCode ^
      error.hashCode ^
      alreadyManaged.hashCode ^
      existingUuid.hashCode ^
      conflictStatus.hashCode ^
      conflictingUuid.hashCode ^
      conflictingName.hashCode ^
      needsConflictDecision.hashCode ^
      canReplace.hashCode ^
      plannedTarget.hashCode ^
      extractorUsed.hashCode ^
      usedUnsafeFallback.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InspectDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          sizeBytes == other.sizeBytes &&
          sha256 == other.sha256 &&
          appType == other.appType &&
          architecture == other.architecture &&
          magicValid == other.magicValid &&
          architectureSupported == other.architectureSupported &&
          truncated == other.truncated &&
          name == other.name &&
          version == other.version &&
          comment == other.comment &&
          iconName == other.iconName &&
          iconFormat == other.iconFormat &&
          iconBytes == other.iconBytes &&
          categories == other.categories &&
          mimeTypes == other.mimeTypes &&
          terminal == other.terminal &&
          website == other.website &&
          startupWmClass == other.startupWmClass &&
          actionNames == other.actionNames &&
          embeddedUpdate == other.embeddedUpdate &&
          embeddedManagerHint == other.embeddedManagerHint &&
          warnings == other.warnings &&
          error == other.error &&
          alreadyManaged == other.alreadyManaged &&
          existingUuid == other.existingUuid &&
          conflictStatus == other.conflictStatus &&
          conflictingUuid == other.conflictingUuid &&
          conflictingName == other.conflictingName &&
          needsConflictDecision == other.needsConflictDecision &&
          canReplace == other.canReplace &&
          plannedTarget == other.plannedTarget &&
          extractorUsed == other.extractorUsed &&
          usedUnsafeFallback == other.usedUnsafeFallback;
}

class KeyValueDto {
  final String key;
  final String value;

  const KeyValueDto({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyValueDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

/// The result of an install, update or removal. Failures that the user can act
/// on (a name conflict, a running app) are reported here, not as errors.
class OutcomeDto {
  final bool ok;
  final bool partial;
  final String message;
  final bool conflict;
  final bool running;
  final AppDto? app;
  final List<String> rolledBack;
  final bool sourceRemoved;

  /// The installation a Replace would target. Set only on a name conflict,
  /// and empty when no single installation is implicated.
  final String conflictUuid;
  final String conflictName;

  const OutcomeDto({
    required this.ok,
    required this.partial,
    required this.message,
    required this.conflict,
    required this.running,
    this.app,
    required this.rolledBack,
    required this.sourceRemoved,
    required this.conflictUuid,
    required this.conflictName,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      partial.hashCode ^
      message.hashCode ^
      conflict.hashCode ^
      running.hashCode ^
      app.hashCode ^
      rolledBack.hashCode ^
      sourceRemoved.hashCode ^
      conflictUuid.hashCode ^
      conflictName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutcomeDto &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          partial == other.partial &&
          message == other.message &&
          conflict == other.conflict &&
          running == other.running &&
          app == other.app &&
          rolledBack == other.rolledBack &&
          sourceRemoved == other.sourceRemoved &&
          conflictUuid == other.conflictUuid &&
          conflictName == other.conflictName;
}

class TaskDto {
  final String id;
  final TaskKindDto kind;
  final TaskStateDto state;
  final String title;
  final String target;
  final int progress;
  final String statusText;
  final String error;
  final bool retryable;

  const TaskDto({
    required this.id,
    required this.kind,
    required this.state,
    required this.title,
    required this.target,
    required this.progress,
    required this.statusText,
    required this.error,
    required this.retryable,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      state.hashCode ^
      title.hashCode ^
      target.hashCode ^
      progress.hashCode ^
      statusText.hashCode ^
      error.hashCode ^
      retryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          state == other.state &&
          title == other.title &&
          target == other.target &&
          progress == other.progress &&
          statusText == other.statusText &&
          error == other.error &&
          retryable == other.retryable;
}

enum TaskKindDto {
  inspect,
  integrate,
  update,
  remove,
  refreshMetadata,
  checkUpdate,
  adopt,
}

enum TaskStateDto { queued, running, cancelling, succeeded, failed, cancelled }

class UpdateFailureDto {
  final String uuid;
  final String name;
  final String manager;
  final String error;

  const UpdateFailureDto({
    required this.uuid,
    required this.name,
    required this.manager,
    required this.error,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^ name.hashCode ^ manager.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateFailureDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          manager == other.manager &&
          error == other.error;
}

class UpdateOfferDto {
  final String uuid;
  final String name;
  final String currentVersion;
  final String availableVersion;
  final String manager;
  final String url;
  final PlatformInt64 downloadSize;
  final String digest;
  final bool reducedVerification;
  final String digestAlgo;
  final String embeddedSource;
  final bool running;

  const UpdateOfferDto({
    required this.uuid,
    required this.name,
    required this.currentVersion,
    required this.availableVersion,
    required this.manager,
    required this.url,
    required this.downloadSize,
    required this.digest,
    required this.reducedVerification,
    required this.digestAlgo,
    required this.embeddedSource,
    required this.running,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      name.hashCode ^
      currentVersion.hashCode ^
      availableVersion.hashCode ^
      manager.hashCode ^
      url.hashCode ^
      downloadSize.hashCode ^
      digest.hashCode ^
      reducedVerification.hashCode ^
      digestAlgo.hashCode ^
      embeddedSource.hashCode ^
      running.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateOfferDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          currentVersion == other.currentVersion &&
          availableVersion == other.availableVersion &&
          manager == other.manager &&
          url == other.url &&
          downloadSize == other.downloadSize &&
          digest == other.digest &&
          reducedVerification == other.reducedVerification &&
          digestAlgo == other.digestAlgo &&
          embeddedSource == other.embeddedSource &&
          running == other.running;
}

class UpdateScanDto {
  final List<UpdateOfferDto> offers;
  final List<UpdateFailureDto> failures;
  final PlatformInt64 skipped;
  final PlatformInt64 checked;
  final bool cancelled;

  const UpdateScanDto({
    required this.offers,
    required this.failures,
    required this.skipped,
    required this.checked,
    required this.cancelled,
  });

  @override
  int get hashCode =>
      offers.hashCode ^
      failures.hashCode ^
      skipped.hashCode ^
      checked.hashCode ^
      cancelled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateScanDto &&
          runtimeType == other.runtimeType &&
          offers == other.offers &&
          failures == other.failures &&
          skipped == other.skipped &&
          checked == other.checked &&
          cancelled == other.cancelled;
}
