// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'common.dart';
import 'dto.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `read_icon`

/// Inspect one AppImage. A file that cannot be read or parsed comes back with
/// `error` set; only an empty path is an error of the call itself.
Future<InspectDto> inspectPath({required String opId, required String path}) =>
    RustLib.instance.api.crateApiInspectInspectPath(opId: opId, path: path);
