// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'common.dart';
import 'dto.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `conflict_candidate`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Integrate one file. `replace_uuid` is used only with `Replace`. With
/// `move_source`, the original goes to the Trash after a verified copy.
Future<OutcomeDto> integrateApp({
  required String opId,
  required String sourcePath,
  required ConflictChoice conflict,
  required String replaceUuid,
  required bool moveSource,
}) => RustLib.instance.api.crateApiIntegrateIntegrateApp(
  opId: opId,
  sourcePath: sourcePath,
  conflict: conflict,
  replaceUuid: replaceUuid,
  moveSource: moveSource,
);

/// How to resolve a name conflict. `Automatic` means the caller has not chosen;
/// the core then refuses and reports the conflict.
enum ConflictChoice { automatic, keepBoth, replace }
