// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'common.dart';
import 'dto.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `find_app`, `remove_with`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// The registered apps, which of them are running, and what discovery finds.
Future<LibraryDto> listLibrary() =>
    RustLib.instance.api.crateApiLibraryListLibrary();

/// One app with its current running state.
Future<AppDto> getApp({required String uuid}) =>
    RustLib.instance.api.crateApiLibraryGetApp(uuid: uuid);

/// Start the app, detached. The manager never waits for it or stops it.
Future<void> launchApp({required String uuid}) =>
    RustLib.instance.api.crateApiLibraryLaunchApp(uuid: uuid);

/// Open the file manager at the app's folder.
Future<void> revealApp({required String uuid}) =>
    RustLib.instance.api.crateApiLibraryRevealApp(uuid: uuid);

/// Replace the app's launch arguments and environment, and rewrite its entry.
Future<AppDto> saveArgumentsAndEnvironment({
  required String uuid,
  required List<String> arguments,
  required List<EnvVarDto> environment,
}) => RustLib.instance.api.crateApiLibrarySaveArgumentsAndEnvironment(
  uuid: uuid,
  arguments: arguments,
  environment: environment,
);

/// Choose how the app checks for updates. The config is the manager's keys.
Future<AppDto> setUpdateSource({
  required String uuid,
  required String manager,
  required List<KeyValueDto> config,
}) => RustLib.instance.api.crateApiLibrarySetUpdateSource(
  uuid: uuid,
  manager: manager,
  config: config,
);

/// Remove the app's update source, so it is no longer checked.
Future<AppDto> unsetUpdateSource({required String uuid}) =>
    RustLib.instance.api.crateApiLibraryUnsetUpdateSource(uuid: uuid);

/// Register an external AppImage. Nothing on disk changes.
Future<AppDto> adoptPath({required String opId, required String path}) =>
    RustLib.instance.api.crateApiLibraryAdoptPath(opId: opId, path: path);

/// Re-read the app's metadata and rewrite its menu entry.
Future<AppDto> refreshMetadata({required String opId, required String uuid}) =>
    RustLib.instance.api.crateApiLibraryRefreshMetadata(opId: opId, uuid: uuid);

/// Remove an app: to the Trash by default, or permanently when asked.
Future<OutcomeDto> removeApp({
  required String opId,
  required String uuid,
  required bool permanent,
}) => RustLib.instance.api.crateApiLibraryRemoveApp(
  opId: opId,
  uuid: uuid,
  permanent: permanent,
);

/// Everything the Library page shows, in one call.
class LibraryDto {
  final List<AppDto> apps;
  final List<DiscoveredDto> discovered;

  const LibraryDto({required this.apps, required this.discovered});

  @override
  int get hashCode => apps.hashCode ^ discovered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryDto &&
          runtimeType == other.runtimeType &&
          apps == other.apps &&
          discovered == other.discovered;
}
