// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'common.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `settings_dto`, `to_core_appearance`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// Read the preferences. This runs at startup, and it first reconciles the
/// login entry with "Check in the background", so an entry left by an earlier
/// build cannot run an ungated check.
Future<SettingsDto> loadSettings() =>
    RustLib.instance.api.crateApiSettingsLoadSettings();

/// Save the given preferences. Each change is written to disk as it is made.
Future<SettingsDto> saveSettings({required SettingsPatchDto patch}) =>
    RustLib.instance.api.crateApiSettingsSaveSettings(patch: patch);

/// Install or remove the login-time check. It only notifies; it never applies.
Future<void> setAutostart({required bool enabled}) =>
    RustLib.instance.api.crateApiSettingsSetAutostart(enabled: enabled);

enum AppearanceChoice { system, light, dark }

/// Every saved preference, plus whether the login-time check is installed.
class SettingsDto {
  final String managedFolder;
  final bool moveSource;
  final bool manageOutsideFolder;
  final bool terminalOmitSuffix;
  final bool backgroundUpdateChecks;
  final bool unsafeExtractionFallback;
  final bool debugLogging;
  final AppearanceChoice appearance;
  final PlatformInt64 maxAppimageBytes;
  final String? loadError;
  final bool autostartEnabled;

  const SettingsDto({
    required this.managedFolder,
    required this.moveSource,
    required this.manageOutsideFolder,
    required this.terminalOmitSuffix,
    required this.backgroundUpdateChecks,
    required this.unsafeExtractionFallback,
    required this.debugLogging,
    required this.appearance,
    required this.maxAppimageBytes,
    this.loadError,
    required this.autostartEnabled,
  });

  @override
  int get hashCode =>
      managedFolder.hashCode ^
      moveSource.hashCode ^
      manageOutsideFolder.hashCode ^
      terminalOmitSuffix.hashCode ^
      backgroundUpdateChecks.hashCode ^
      unsafeExtractionFallback.hashCode ^
      debugLogging.hashCode ^
      appearance.hashCode ^
      maxAppimageBytes.hashCode ^
      loadError.hashCode ^
      autostartEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsDto &&
          runtimeType == other.runtimeType &&
          managedFolder == other.managedFolder &&
          moveSource == other.moveSource &&
          manageOutsideFolder == other.manageOutsideFolder &&
          terminalOmitSuffix == other.terminalOmitSuffix &&
          backgroundUpdateChecks == other.backgroundUpdateChecks &&
          unsafeExtractionFallback == other.unsafeExtractionFallback &&
          debugLogging == other.debugLogging &&
          appearance == other.appearance &&
          maxAppimageBytes == other.maxAppimageBytes &&
          loadError == other.loadError &&
          autostartEnabled == other.autostartEnabled;
}

/// A partial update. Only the fields that are set are changed.
class SettingsPatchDto {
  final String? managedFolder;
  final bool? moveSource;
  final bool? manageOutsideFolder;
  final bool? terminalOmitSuffix;
  final bool? backgroundUpdateChecks;
  final bool? unsafeExtractionFallback;
  final bool? debugLogging;
  final AppearanceChoice? appearance;
  final PlatformInt64? maxAppimageBytes;

  const SettingsPatchDto({
    this.managedFolder,
    this.moveSource,
    this.manageOutsideFolder,
    this.terminalOmitSuffix,
    this.backgroundUpdateChecks,
    this.unsafeExtractionFallback,
    this.debugLogging,
    this.appearance,
    this.maxAppimageBytes,
  });

  static Future<SettingsPatchDto> default_() =>
      RustLib.instance.api.crateApiSettingsSettingsPatchDtoDefault();

  @override
  int get hashCode =>
      managedFolder.hashCode ^
      moveSource.hashCode ^
      manageOutsideFolder.hashCode ^
      terminalOmitSuffix.hashCode ^
      backgroundUpdateChecks.hashCode ^
      unsafeExtractionFallback.hashCode ^
      debugLogging.hashCode ^
      appearance.hashCode ^
      maxAppimageBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsPatchDto &&
          runtimeType == other.runtimeType &&
          managedFolder == other.managedFolder &&
          moveSource == other.moveSource &&
          manageOutsideFolder == other.manageOutsideFolder &&
          terminalOmitSuffix == other.terminalOmitSuffix &&
          backgroundUpdateChecks == other.backgroundUpdateChecks &&
          unsafeExtractionFallback == other.unsafeExtractionFallback &&
          debugLogging == other.debugLogging &&
          appearance == other.appearance &&
          maxAppimageBytes == other.maxAppimageBytes;
}
