// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The bridge's own version. Synchronous, so it doubles as a cheap round-trip check.
String bridgeVersion() => RustLib.instance.api.crateApiSystemBridgeVersion();

/// The application version, as the core reports it.
Future<String> appVersion() => RustLib.instance.api.crateApiSystemAppVersion();

/// Running tasks first, then the finished ones, as the Tasks page lists them.
Future<List<TaskDto>> listTasks() =>
    RustLib.instance.api.crateApiSystemListTasks();

/// Remove finished tasks from the Tasks page.
Future<void> clearFinishedTasks() =>
    RustLib.instance.api.crateApiSystemClearFinishedTasks();

/// Ask a running operation to stop. Returns false when it is not running.
Future<bool> cancelTask({required String opId}) =>
    RustLib.instance.api.crateApiSystemCancelTask(opId: opId);
