// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'common.dart';
import 'dto.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `failure_dto`, `percent`, `report_apply_event`

/// Check one app's update source for "Check for update" on its Detail page.
/// It reports what the source offers and never downloads or applies anything:
/// the installed file and its version stay as they are. Applying is the
/// separate Update action. A check is not listed on the Tasks page.
Future<UpdateCheckDto> checkOneUpdate({required String uuid}) =>
    RustLib.instance.api.crateApiUpdatesCheckOneUpdate(uuid: uuid);

/// Check every app that has an update source. Apps without one are skipped,
/// and apps that could not be checked are listed as failures.
Future<UpdateScanDto> checkUpdates({required String opId}) =>
    RustLib.instance.api.crateApiUpdatesCheckUpdates(opId: opId);

/// Apply one app's update. A running app is refused unless `force` is set.
Future<OutcomeDto> applyUpdate({
  required String opId,
  required String uuid,
  required bool force,
}) => RustLib.instance.api.crateApiUpdatesApplyUpdate(
  opId: opId,
  uuid: uuid,
  force: force,
);

/// Check every app, then apply each offer in turn. Running apps are skipped
/// unless `force` is set. Progress is reported to the Tasks page per app.
Future<BatchDto> applyAllUpdates({required String opId, required bool force}) =>
    RustLib.instance.api.crateApiUpdatesApplyAllUpdates(
      opId: opId,
      force: force,
    );
